# Generated by Django 6.1.1 on 2026-09-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_moviesession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genres",
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="genres", to="db.genre"),
        ),
    ]
